# fly.toml app configuration file generated for hyohyo-pokedex on 2023-07-09T14:10:17-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hyohyo-pokedex"
primary_region = "lax"

[env]
  PORT = "8080"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.17.0"

[[http_service]]
  internal_port = 8080
  processes = ["app"]

[[services.http_checks]]
  interval = 10000
  grace_period = "5s"
  method = "get"
  path = "/health"
  protocol = "http"
  restart_limit = 0
  timeout = 2000
  tls_skip_verify = true

[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"