# fly.toml app configuration file generated for hyohyo-pokedex on 2023-07-09T14:10:17-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hyohyo-pokedex"
primary_region = "lax"

[env]
  PORT = "8080"

[build]
  [build.args]
    NODE_VERSION = "16.17.0"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[[services]]
  processes = ["app"]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
  force_https = true
  handlers = ["http"]
  port = 80

[[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[[services.http_checks]]
  interval = 10000
  grace_period = "5s"
  method = "get"
  path = "/health"
  protocol = "http"
  restart_limit = 0
  timeout = 2000
  tls_skip_verify = true

[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"